# Work on Sample data from League of Legends

In [2]:
import pandas as pd
import json

file = '../raw_data/games_dump.json'
with open(file) as data_file:    
    data = json.load(data_file) 
data = data[:]
len(data)

18254

In [3]:
data[0]

{'id': 2,
 'start': '2011-06-18T09:45:00+00:00',
 'patch': 'None.None',
 'winner': 'BLUE',
 'duration': 1777,
 'video': 'https://www.youtube.com/watch?v=98OWfh2OFPc',
 'teams': {'BLUE': {'name': 'Fnatic',
   'total_turret_kills': 0,
   'total_inhibitor_kills': None,
   'total_rift_herald_kills': 0,
   'total_dragon_kills': 0,
   'total_baron_kills': 0,
   'players': [{'name': 'Wewillfailer',
     'champion_name': 'Malzahar',
     'champion_id': 90,
     'gd_15': None,
     'kills_assists_15': 0,
     'deaths_15': 0,
     'gold_share_post_15': None,
     'damage_share': None,
     'jungle_proximity': None,
     'support_proximity': None,
     'total_gold': None,
     'total_cs': None,
     'total_kills': None,
     'total_monster_kills': None,
     'total_assists': None,
     'total_deaths': None,
     'total_vision_score': None,
     'total_damage_taken': None,
     'total_damage_dealt': None,
     'trueskill_sigma': 8.333333,
     'trueskill_mu': 20.0,
     'win': True,
     'side': '

In [4]:
data[0].keys()

dict_keys(['id', 'start', 'patch', 'winner', 'duration', 'video', 'teams', 'picks_bans'])

In [5]:
data[0]['teams'].keys()

dict_keys(['BLUE', 'RED'])

In [6]:
data[0]['teams']['BLUE'].keys()

dict_keys(['name', 'total_turret_kills', 'total_inhibitor_kills', 'total_rift_herald_kills', 'total_dragon_kills', 'total_baron_kills', 'players'])

In [7]:
data[0]['teams']['BLUE']['players'][0].keys()

dict_keys(['name', 'champion_name', 'champion_id', 'gd_15', 'kills_assists_15', 'deaths_15', 'gold_share_post_15', 'damage_share', 'jungle_proximity', 'support_proximity', 'total_gold', 'total_cs', 'total_kills', 'total_monster_kills', 'total_assists', 'total_deaths', 'total_vision_score', 'total_damage_taken', 'total_damage_dealt', 'trueskill_sigma', 'trueskill_mu', 'win', 'side'])

### To remove
video, team_name, 'total_monster_kills', 'damage_share', 'total_vision_score'

## Normalize the JSON file into a Pandas DataFrame

Data is structured in a JSON structure that is inconvinient for data analysis. Converting nested JSON structures to Pandas DataFrames using https://medium.com/swlh/converting-nested-json-structures-to-pandas-dataframes-e8106c59976e

In [8]:
#Normalize the teams input
df_normalized_teams = pd.json_normalize(data)
df_normalized_teams.head()

id                      start      patch winner  duration  \
0   2  2011-06-18T09:45:00+00:00  None.None   BLUE    1777.0   
1   4  2011-06-18T11:00:00+00:00  None.None   BLUE    1735.0   
2   5  2011-06-18T12:15:00+00:00  None.None   BLUE    1453.0   
3   7  2011-06-18T14:30:00+00:00  None.None    RED    2260.0   
4   9  2011-06-18T16:00:00+00:00  None.None   BLUE    2185.0   

                                         video picks_bans teams.BLUE.name  \
0  https://www.youtube.com/watch?v=98OWfh2OFPc         []          Fnatic   
1  https://www.youtube.com/watch?v=bEMJx-g0yk8         []      Epik Gamer   
2  https://www.youtube.com/watch?v=5jXjps7DMD8         []            None   
3  https://www.youtube.com/watch?v=Y5LunOkh738         []             TSM   
4  https://www.youtube.com/watch?v=7qiyiYC6XUs         []            None   

   teams.BLUE.total_turret_kills  teams.BLUE.total_inhibitor_kills  ...  \
0                            0.0                               NaN  ...   
1                            0.0                               NaN  ...   
2                            0.0                               NaN  ...   
3                            0.0                               NaN  ...   
4                            0.0                               NaN  ...   

   teams.BLUE.total_dragon_kills  teams.BLUE.total_baron_kills  \
0                            0.0                           0.0   
1                            0.0                           0.0   
2                            0.0                           0.0   
3                            0.0                           0.0   
4                            0.0                           0.0   

                                  teams.BLUE.players teams.RED.name  \
0  [{'name': 'Wewillfailer', 'champion_name': 'Ma...           None   
1  [{'name': 'Westrice', 'champion_name': 'Corki'...           None   
2  [{'name': 'SOAZ', 'champion_name': 'Nidalee', ...           None   
3  [{'name': 'The Rain Man', 'champion_name': 'Ch...           None   
4  [{'name': 'Kev1n', 'champion_name': 'Nidalee',...           None   

  teams.RED.total_turret_kills  teams.RED.total_inhibitor_kills  \
0                          0.0                              NaN   
1                          0.0                              NaN   
2                          0.0                              NaN   
3                          0.0                              NaN   
4                          0.0                              NaN   

   teams.RED.total_rift_herald_kills  teams.RED.total_dragon_kills  \
0                                0.0                           0.0   
1                                0.0                           0.0   
2                                0.0                           0.0   
3                                0.0                           0.0   
4                                0.0                           0.0   

   teams.RED.total_baron_kills  \
0                          0.0   
1                          0.0   
2                          0.0   
3                          0.0   
4                          0.0   

                                   teams.RED.players  
0  [{'name': None, 'champion_name': 'Karthus', 'c...  
1  [{'name': None, 'champion_name': 'Malzahar', '...  
2  [{'name': None, 'champion_name': 'Malzahar', '...  
3  [{'name': None, 'champion_name': 'Nocturne', '...  
4  [{'name': None, 'champion_name': 'Nunu & Willu...  

[5 rows x 21 columns]

In [9]:
df_normalized_teams.drop('video', axis=1, inplace = True)

In [10]:
df_normalized_teams.drop(['teams.BLUE.name', 'teams.RED.name'], axis=1, inplace=True)

In [11]:
df_normalized_teams['teams.BLUE.players'].explode()

0        {'name': 'Wewillfailer', 'champion_name': 'Mal...
0        {'name': 'Cyanide', 'champion_name': 'Nunu & W...
0        {'name': 'Shushei', 'champion_name': 'Alistar'...
0        {'name': 'LaMiaZeaLoT', 'champion_name': 'Cork...
0        {'name': 'Mellisan', 'champion_name': 'Janna',...
                               ...                        
18253    {'name': 'Flaai', 'champion_name': 'Sett', 'ch...
18253    {'name': 'Adampongo', 'champion_name': 'Jarvan...
18253    {'name': 'Necropolisak', 'champion_name': 'Ryz...
18253    {'name': 'Kneza', 'champion_name': 'Lucian', '...
18253    {'name': 'Phenix', 'champion_name': 'Lulu', 'c...
Name: teams.BLUE.players, Length: 91270, dtype: object

In [12]:
df_normalized_BLUE = pd.json_normalize(df_normalized_teams['teams.BLUE.players'].explode())
df_normalized_BLUE

name   champion_name  champion_id  gd_15  kills_assists_15  \
0      Wewillfailer        Malzahar           90    NaN               0.0   
1           Cyanide  Nunu & Willump           20    NaN               0.0   
2           Shushei         Alistar           12    NaN               0.0   
3       LaMiaZeaLoT           Corki           42    NaN               0.0   
4          Mellisan           Janna           40    NaN               0.0   
...             ...             ...          ...    ...               ...   
91265         Flaai            Sett          875    NaN               NaN   
91266     Adampongo       Jarvan IV           59    NaN               NaN   
91267  Necropolisak            Ryze           13    NaN               NaN   
91268         Kneza          Lucian          236    NaN               NaN   
91269        Phenix            Lulu          117    NaN               NaN   

       deaths_15  gold_share_post_15  damage_share  jungle_proximity  \
0            0.0                 NaN           NaN               NaN   
1            0.0                 NaN           NaN               NaN   
2            0.0                 NaN           NaN               NaN   
3            0.0                 NaN           NaN               NaN   
4            0.0                 NaN           NaN               NaN   
...          ...                 ...           ...               ...   
91265        NaN                 NaN           NaN               NaN   
91266        NaN                 NaN           NaN               NaN   
91267        NaN                 NaN           NaN               NaN   
91268        NaN                 NaN           NaN               NaN   
91269        NaN                 NaN           NaN               NaN   

       support_proximity  ...  total_monster_kills  total_assists  \
0                    NaN  ...                  NaN            NaN   
1                    NaN  ...                  NaN            NaN   
2                    NaN  ...                  NaN            NaN   
3                    NaN  ...                  NaN            NaN   
4                    NaN  ...                  NaN            NaN   
...                  ...  ...                  ...            ...   
91265                NaN  ...                 16.0            6.0   
91266                NaN  ...                152.0           14.0   
91267                NaN  ...                 35.0            4.0   
91268                NaN  ...                 40.0            5.0   
91269                NaN  ...                  0.0           19.0   

       total_deaths  total_vision_score  total_damage_taken  \
0               NaN                 NaN                 NaN   
1               NaN                 NaN                 NaN   
2               NaN                 NaN                 NaN   
3               NaN                 NaN                 NaN   
4               NaN                 NaN                 NaN   
...             ...                 ...                 ...   
91265           4.0                51.0             28321.0   
91266           2.0                46.0             32735.0   
91267           2.0                28.0             15094.0   
91268           0.0                62.0             19019.0   
91269           4.0                60.0             12312.0   

       total_damage_dealt  trueskill_sigma  trueskill_mu   win  side  
0                     NaN         8.333333     20.000000  True  BLUE  
1                     NaN         8.333333     20.000000  True  BLUE  
2                     NaN         8.333333     20.000000  True  BLUE  
3                     NaN         8.333333     20.000000  True  BLUE  
4                     NaN         8.333333     20.000000  True  BLUE  
...                   ...              ...           ...   ...   ...  
91265            115423.0         4.829746     34.512520  True  BLUE  
91266            170233.0         6.328289     25.607258  True  BLUE  


In [13]:
df_normalized_RED = pd.json_normalize(df_normalized_teams['teams.RED.players'].explode(), )
df_normalized_RED

name champion_name  champion_id  gd_15  \
0                       None       Karthus           30    NaN   
1                       None         Amumu           32    NaN   
2                       None  Twisted Fate            4    NaN   
3                       None         Garen           86    NaN   
4                       None         Taric           44    NaN   
...                      ...           ...          ...    ...   
91265                 Kulvas       Camille          164    NaN   
91266  Hiro (Nguyên Đại Hải)  Miss Fortune           21    NaN   
91267               Jackisek       LeBlanc            7    NaN   
91268                 Smarty          Nami          267    NaN   
91269                 Savero         Viego          234    NaN   

       kills_assists_15  deaths_15  gold_share_post_15  damage_share  \
0                   0.0        0.0                 NaN           NaN   
1                   0.0        0.0                 NaN           NaN   
2                   0.0        0.0                 NaN           NaN   
3                   0.0        0.0                 NaN           NaN   
4                   0.0        0.0                 NaN           NaN   
...                 ...        ...                 ...           ...   
91265               NaN        NaN                 NaN           NaN   
91266               NaN        NaN                 NaN           NaN   
91267               NaN        NaN                 NaN           NaN   
91268               NaN        NaN                 NaN           NaN   
91269               NaN        NaN                 NaN           NaN   

       jungle_proximity  support_proximity  ...  total_monster_kills  \
0                   NaN                NaN  ...                  NaN   
1                   NaN                NaN  ...                  NaN   
2                   NaN                NaN  ...                  NaN   
3                   NaN                NaN  ...                  NaN   
4                   NaN                NaN  ...                  NaN   
...                 ...                ...  ...                  ...   
91265               NaN                NaN  ...                 16.0   
91266               NaN                NaN  ...                  9.0   
91267               NaN                NaN  ...                 12.0   
91268               NaN                NaN  ...                  0.0   
91269               NaN                NaN  ...                158.0   

       total_assists  total_deaths  total_vision_score  total_damage_taken  \
0                NaN           NaN                 NaN                 NaN   
1                NaN           NaN                 NaN                 NaN   
2                NaN           NaN                 NaN                 NaN   
3                NaN           NaN                 NaN                 NaN   
4                NaN           NaN                 NaN                 NaN   
...              ...           ...                 ...                 ...   
91265            4.0           5.0                45.0             27259.0   
91266            0.0           5.0                40.0             12090.0   
91267            7.0           3.0                38.0             23435.0   
91268            9.0           6.0                82.0             11427.0   
91269            3.0           3.0                29.0             27727.0   

       total_damage_dealt  trueskill_sigma  trueskill_mu    win  side  
0                     NaN              NaN           NaN  False   RED  
1                     NaN              NaN           NaN  False   RED  
2                     NaN              NaN           NaN  False   RED  
3                     NaN              NaN           NaN  False   RED  
4                     NaN              NaN           NaN  False   RED  
...                   ...              ...           ...    ...   ...  
91265            169260.0         3.942188     32.053300  Fa

### Get the game id to properly analyze the data

We have two different dataframes for team Blue and team Red, we can merge them on the game id. This will also be useful when we want to come back for the y parameter! 

In [14]:
# Extract the index corresponding to the game id 
get_index = df_normalized_teams['id'].tolist()
get_index[:10], len(get_index)

([2, 4, 5, 7, 9, 12, 38, 39, 41, 43], 18254)

In [15]:
import numpy as np

index_preproc = np.asarray([[index] * 5 for index in get_index])
index_preproc.shape

(18254, 5)

In [16]:
#reshape the array to 1D
## 5 is because there are 5 players per team
index_teams = index_preproc.reshape(len(df_normalized_teams) * 5).tolist()
index_teams[0:12]

[2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 5, 5]

In [17]:
df_normalized_RED['index_teams'] = index_teams
df_normalized_BLUE['index_teams'] = index_teams

In [18]:
df_normalized_BLUE

name   champion_name  champion_id  gd_15  kills_assists_15  \
0      Wewillfailer        Malzahar           90    NaN               0.0   
1           Cyanide  Nunu & Willump           20    NaN               0.0   
2           Shushei         Alistar           12    NaN               0.0   
3       LaMiaZeaLoT           Corki           42    NaN               0.0   
4          Mellisan           Janna           40    NaN               0.0   
...             ...             ...          ...    ...               ...   
91265         Flaai            Sett          875    NaN               NaN   
91266     Adampongo       Jarvan IV           59    NaN               NaN   
91267  Necropolisak            Ryze           13    NaN               NaN   
91268         Kneza          Lucian          236    NaN               NaN   
91269        Phenix            Lulu          117    NaN               NaN   

       deaths_15  gold_share_post_15  damage_share  jungle_proximity  \
0            0.0                 NaN           NaN               NaN   
1            0.0                 NaN           NaN               NaN   
2            0.0                 NaN           NaN               NaN   
3            0.0                 NaN           NaN               NaN   
4            0.0                 NaN           NaN               NaN   
...          ...                 ...           ...               ...   
91265        NaN                 NaN           NaN               NaN   
91266        NaN                 NaN           NaN               NaN   
91267        NaN                 NaN           NaN               NaN   
91268        NaN                 NaN           NaN               NaN   
91269        NaN                 NaN           NaN               NaN   

       support_proximity  ...  total_assists  total_deaths  \
0                    NaN  ...            NaN           NaN   
1                    NaN  ...            NaN           NaN   
2                    NaN  ...            NaN           NaN   
3                    NaN  ...            NaN           NaN   
4                    NaN  ...            NaN           NaN   
...                  ...  ...            ...           ...   
91265                NaN  ...            6.0           4.0   
91266                NaN  ...           14.0           2.0   
91267                NaN  ...            4.0           2.0   
91268                NaN  ...            5.0           0.0   
91269                NaN  ...           19.0           4.0   

       total_vision_score  total_damage_taken  total_damage_dealt  \
0                     NaN                 NaN                 NaN   
1                     NaN                 NaN                 NaN   
2                     NaN                 NaN                 NaN   
3                     NaN                 NaN                 NaN   
4                     NaN                 NaN                 NaN   
...                   ...                 ...                 ...   
91265                51.0             28321.0            115423.0   
91266                46.0             32735.0            170233.0   
91267                28.0             15094.0            173262.0   
91268                62.0             19019.0            305263.0   
91269                60.0             12312.0             14282.0   

       trueskill_sigma  trueskill_mu   win  side  index_teams  
0             8.333333     20.000000  True  BLUE            2  
1             8.333333     20.000000  True  BLUE            2  
2             8.333333     20.000000  True  BLUE            2  
3             8.333333     20.000000  True  BLUE            2  
4             8.333333     20.000000  True  BLUE            2  
...                ...           ...   ...   ...          ...  
91265         4.829746     34.512520  True  BLUE        19525  
91266         6.328289     25.607258  True  BLUE        19525  
91267         5.523678     28.171322  True  BLUE        19525  
91268      

In [19]:
df_normalized_RED

name champion_name  champion_id  gd_15  \
0                       None       Karthus           30    NaN   
1                       None         Amumu           32    NaN   
2                       None  Twisted Fate            4    NaN   
3                       None         Garen           86    NaN   
4                       None         Taric           44    NaN   
...                      ...           ...          ...    ...   
91265                 Kulvas       Camille          164    NaN   
91266  Hiro (Nguyên Đại Hải)  Miss Fortune           21    NaN   
91267               Jackisek       LeBlanc            7    NaN   
91268                 Smarty          Nami          267    NaN   
91269                 Savero         Viego          234    NaN   

       kills_assists_15  deaths_15  gold_share_post_15  damage_share  \
0                   0.0        0.0                 NaN           NaN   
1                   0.0        0.0                 NaN           NaN   
2                   0.0        0.0                 NaN           NaN   
3                   0.0        0.0                 NaN           NaN   
4                   0.0        0.0                 NaN           NaN   
...                 ...        ...                 ...           ...   
91265               NaN        NaN                 NaN           NaN   
91266               NaN        NaN                 NaN           NaN   
91267               NaN        NaN                 NaN           NaN   
91268               NaN        NaN                 NaN           NaN   
91269               NaN        NaN                 NaN           NaN   

       jungle_proximity  support_proximity  ...  total_assists  total_deaths  \
0                   NaN                NaN  ...            NaN           NaN   
1                   NaN                NaN  ...            NaN           NaN   
2                   NaN                NaN  ...            NaN           NaN   
3                   NaN                NaN  ...            NaN           NaN   
4                   NaN                NaN  ...            NaN           NaN   
...                 ...                ...  ...            ...           ...   
91265               NaN                NaN  ...            4.0           5.0   
91266               NaN                NaN  ...            0.0           5.0   
91267               NaN                NaN  ...            7.0           3.0   
91268               NaN                NaN  ...            9.0           6.0   
91269               NaN                NaN  ...            3.0           3.0   

       total_vision_score  total_damage_taken  total_damage_dealt  \
0                     NaN                 NaN                 NaN   
1                     NaN                 NaN                 NaN   
2                     NaN                 NaN                 NaN   
3                     NaN                 NaN                 NaN   
4                     NaN                 NaN                 NaN   
...                   ...                 ...                 ...   
91265                45.0             27259.0            169260.0   
91266                40.0             12090.0            177612.0   
91267                38.0             23435.0            125024.0   
91268                82.0             11427.0             11595.0   
91269                29.0             27727.0            182118.0   

       trueskill_sigma  trueskill_mu    win  side  index_teams  
0                  NaN           NaN  False   RED            2  
1                  NaN           NaN  False   RED            2  
2                  NaN           NaN  False   RED            2  
3                  NaN           NaN  False   RED            2  
4                  NaN           NaN  False   RED            2  
...                ...           ...    ...   ...          ...  
91265         3.942188     32.053300  False   RED        19525  
91266         3.647015     26.539326  False   RED       

There are 3 created dataframes important in this section:
```df_normalized_teams, df_normalized_BLUE and df_normalized_RED```

# Preprocess the data

## For the team data

In [20]:
df_normalized_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18254 entries, 0 to 18253
Data columns (total 18 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   id                                  18254 non-null  int64  
 1   start                               18254 non-null  object 
 2   patch                               18254 non-null  object 
 3   winner                              18254 non-null  object 
 4   duration                            18248 non-null  float64
 5   picks_bans                          18254 non-null  object 
 6   teams.BLUE.total_turret_kills       18248 non-null  float64
 7   teams.BLUE.total_inhibitor_kills    11295 non-null  float64
 8   teams.BLUE.total_rift_herald_kills  15761 non-null  float64
 9   teams.BLUE.total_dragon_kills       18248 non-null  float64
 10  teams.BLUE.total_baron_kills        18248 non-null  float64
 11  teams.BLUE.players                  18254

### Get the year the game was played

In [23]:
df_normalized_teams['start'] = pd.to_datetime(df_normalized_teams['start'])
df_normalized_teams['year'] = pd.DatetimeIndex(df_normalized_teams['start']).year
games_year = df_normalized_teams.year.unique()
games_year

array([2011, 2012, 2013, 2021, 2015, 2016, 2014])

In [26]:
#games played every year
for year in games_year:
    N_games = len(df_normalized_teams[df_normalized_teams['year'] == year])
    print(f'Number of games in {year}: {N_games}')

Number of games in 2011: 28
Number of games in 2012: 428
Number of games in 2013: 1303
Number of games in 2021: 14003
Number of games in 2015: 1544
Number of games in 2016: 204
Number of games in 2014: 744


In [43]:
#Use games only from 2021(?)
def choose_years_to_work(df, *args):
    years_dict = {}
    for year in args:
        years_dict[year] = df[df['year'] == year]
    return pd.concat(years_dict)

choose_years_to_work(df_normalized_teams, 2021)

id                     start  patch winner  duration  \
2021 22     19158 2021-01-01 00:00:00+00:00  11.19   BLUE       NaN   
     135    19162 2021-01-01 00:00:00+00:00  11.19   BLUE       NaN   
     161    19166 2021-01-01 00:00:00+00:00  11.19   BLUE       NaN   
     225    19170 2021-01-01 00:00:00+00:00  11.19   BLUE       NaN   
     238     1297 2021-01-11 16:33:13+00:00   11.1    RED    1666.0   
...           ...                       ...    ...    ...       ...   
     18249  19521 2021-11-07 15:02:32+00:00  11.21   BLUE    1576.0   
     18250  19522 2021-11-07 15:52:33+00:00  11.21   BLUE    2299.0   
     18251  19523 2021-11-07 17:02:12+00:00  11.21    RED    1467.0   
     18252  19524 2021-11-07 17:51:39+00:00  11.21    RED    2053.0   
     18253  19525 2021-11-07 18:54:44+00:00  11.21   BLUE    2048.0   

                                                   picks_bans  \
2021 22                                                    []   
     135                                                   []   
     161                                                   []   
     225                                                   []   
     238                                                   []   
...                                                       ...   
     18249  [{'ban': True, 'champion_id': 0, 'champion_nam...   
     18250  [{'ban': True, 'champion_id': 0, 'champion_nam...   
     18251  [{'ban': True, 'champion_id': 0, 'champion_nam...   
     18252  [{'ban': True, 'champion_id': 0, 'champion_nam...   
     18253  [{'ban': True, 'champion_id': 0, 'champion_nam...   

            teams.BLUE.total_turret_kills  teams.BLUE.total_inhibitor_kills  \
2021 22                               NaN                               NaN   
     135                              NaN                               NaN   
     161                              NaN                               NaN   
     225                              NaN                               NaN   
     238                              2.0                               0.0   
...                                   ...                               ...   
     18249                           10.0                               1.0   
     18250                            9.0                               1.0   
     18251                            5.0                               0.0   
     18252                            7.0                               2.0   
     18253                            8.0                               1.0   

            teams.BLUE.total_rift_herald_kills  teams.BLUE.total_dragon_kills  \
2021 22                                    NaN                            NaN   
     135                                   NaN                            NaN   
     161                                   NaN                            NaN   
     225                                   NaN                            NaN   
     238                                   2.0                            0.0   
...                                        ...                            ...   
     18249                                 2.0                            2.0   
     18250                                 2.0                            4.0   
     18251                                 1.0                            1.0   
     18252                                 2.0                            1.0   
     18253                                 1.0                            4.0   

            teams.BLUE.total_baron_kills  \
2021 22                              NaN   
     135                             NaN   
     161                             NaN   
     225                             NaN   
     238                             0.0   
...                                  ...   
     18249                           1.0   
     18250                           1.0   
     18251                           0.0   
     18252         

In [168]:
# We don't need the rest of the date so we can drop the data
df_normalized_teams.drop('start', axis=1, inplace=True)

In [190]:
winner = [1 if value == 'BLUE' else 0 for value in df_normalized_teams.winner]
len(winner), sum(winner)

(2000, 1053)

In [194]:
from sklearn.preprocessing import LabelEncoder

y = LabelEncoder().fit(df_normalized_teams.winner).transform(df_normalized_teams.winner)
y

array([1, 1, 1, ..., 1, 1, 0])

### Check for null data

In [204]:
df_normalized_teams['teams.BLUE.total_inhibitor_kills'].unique()

array([1., 0., 2., 3., 4., 5., 6., 7.])

In [213]:
median_BLUE_total_inhibitor_kills = df_normalized_teams['teams.BLUE.total_inhibitor_kills'].median()
df_normalized_teams['teams.BLUE.total_inhibitor_kills'] = df_normalized_teams[
            'teams.BLUE.total_inhibitor_kills'].replace(np.nan, median_BLUE_total_inhibitor_kills)

df_normalized_teams['teams.BLUE.total_inhibitor_kills'].unique(), median_BLUE_total_inhibitor_kills

(array([1., 0., 2., 3., 4., 5., 6., 7.]), 1.0)

In [210]:
df_normalized_teams['teams.BLUE.total_rift_herald_kills'].unique()

array([nan,  2.,  0.,  1.])

In [212]:
median_BLUE_total_rift_herald_kills = df_normalized_teams['teams.BLUE.total_rift_herald_kills'].median()
df_normalized_teams['teams.BLUE.total_rift_herald_kills'] = df_normalized_teams[
            'teams.BLUE.total_rift_herald_kills'].replace(np.nan, median_BLUE_total_rift_herald_kills)

df_normalized_teams['teams.BLUE.total_rift_herald_kills'].unique(), median_BLUE_total_rift_herald_kills

(array([1., 2., 0.]), 1.0)

In [158]:
df_normalized_teams['teams.RED.total_inhibitor_kills'].unique()

array([nan,  2.,  0.,  1.,  3.,  5.,  4.,  6.])

In [214]:
median_RED_total_inhibitor_kills = df_normalized_teams['teams.RED.total_inhibitor_kills'].median()
df_normalized_teams['teams.RED.total_inhibitor_kills'] = df_normalized_teams[
            'teams.RED.total_inhibitor_kills'].replace(np.nan, median_RED_total_inhibitor_kills)

df_normalized_teams['teams.RED.total_inhibitor_kills'].unique(), median_RED_total_inhibitor_kills

(array([0., 2., 1., 3., 5., 4., 6.]), 0.0)

In [157]:
df_normalized_teams['teams.RED.total_rift_herald_kills'].unique()

array([nan,  0.,  2.,  1.])

In [215]:
median_RED_total_rift_herald_kills = df_normalized_teams['teams.RED.total_rift_herald_kills'].median()
df_normalized_teams['teams.RED.total_rift_herald_kills'] = df_normalized_teams[
            'teams.RED.total_rift_herald_kills'].replace(np.nan, median_RED_total_rift_herald_kills)

df_normalized_teams['teams.RED.total_rift_herald_kills'].unique(), median_RED_total_rift_herald_kills

(array([1., 0., 2.]), 1.0)

## For the players data

In [171]:
df_normalized_BLUE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   name                 10000 non-null  object 
 1   champion_name        10000 non-null  object 
 2   gd_15                7230 non-null   float64
 3   kills_assists_15     9315 non-null   float64
 4   deaths_15            9315 non-null   float64
 5   gold_share_post_15   260 non-null    float64
 6   damage_share         8720 non-null   float64
 7   jungle_proximity     7230 non-null   float64
 8   support_proximity    7230 non-null   float64
 9   total_cs             9405 non-null   float64
 10  total_kills          9405 non-null   float64
 11  total_monster_kills  9042 non-null   float64
 12  total_assists        9405 non-null   float64
 13  total_deaths         9405 non-null   float64
 14  total_damage_taken   9375 non-null   float64
 15  total_vision_score   9325 non-null   

In [196]:
df_normalized_BLUE.columns

Index(['name', 'champion_name', 'gd_15', 'kills_assists_15', 'deaths_15',
       'gold_share_post_15', 'damage_share', 'jungle_proximity',
       'support_proximity', 'total_cs', 'total_kills', 'total_monster_kills',
       'total_assists', 'total_deaths', 'total_damage_taken',
       'total_vision_score'],
      dtype='object')

In [229]:
for column in df_normalized_BLUE.columns[2:]:
    print(column, '->', df_normalized_BLUE[column].median())
    print(column, '->', df_normalized_BLUE[column].mean())
    print(column, '->', df_normalized_BLUE[column].mode())
    print(' ')

gd_15 -> 80.0
gd_15 -> 81.03706777316737
gd_15 -> 0     70.0
1    344.0
dtype: float64
 
kills_assists_15 -> 1.0
kills_assists_15 -> 1.8892109500805152
kills_assists_15 -> 0    0.0
dtype: float64
 
deaths_15 -> 0.0
deaths_15 -> 0.6718196457326893
deaths_15 -> 0    0.0
dtype: float64
 
gold_share_post_15 -> 0.34958982
gold_share_post_15 -> 0.4392004267615386
gold_share_post_15 -> 0    1.0
dtype: float64
 
damage_share -> 0.20194653
damage_share -> 0.2000000001534396
damage_share -> 0    0.186096
1    0.274648
dtype: float64
 
jungle_proximity -> 0.19450798
jungle_proximity -> 0.33486622220230877
jungle_proximity -> 0    1.0
dtype: float64
 
support_proximity -> 0.242924215
support_proximity -> 0.4061813671669669
support_proximity -> 0    1.0
dtype: float64
 
total_cs -> 208.0
total_cs -> 193.42977139819246
total_cs -> 0    33.0
dtype: float64
 
total_kills -> 2.0
total_kills -> 2.993939393939394
total_kills -> 0    1.0
dtype: float64
 
total_monster_kills -> 14.0
total_monster_kills -> 

In [197]:
df_normalized_BLUE.champion_name

0            Shen
1            Udyr
2         LeBlanc
3         Kog'Maw
4            Lulu
          ...    
9995         Sett
9996    Jarvan IV
9997         Ryze
9998       Lucian
9999         Lulu
Name: champion_name, Length: 10000, dtype: object