# Work on Sample data from League of Legends

In [139]:
import pandas as pd
import json

file = '../raw_data/games_dump.json'
with open(file) as data_file:    
    data = json.load(data_file) 
data = data[-2000:]
len(data)

2000

In [19]:
data[0]

{'id': 9498,
 'start': '2021-06-20T07:59:21+00:00',
 'patch': '11.11',
 'winner': 'RED',
 'duration': 3465,
 'video': 'https://v.qq.com/x/page/l3254kzrmhg.html',
 'teams': {'BLUE': {'name': 'Young Miracles',
   'total_turret_kills': 4,
   'total_inhibitor_kills': None,
   'total_rift_herald_kills': None,
   'total_dragon_kills': 2,
   'total_baron_kills': 1,
   'players': [{'name': 'Fangyuan',
     'champion_name': 'Shen',
     'gd_15': None,
     'kills_assists_15': 0,
     'deaths_15': 0,
     'gold_share_post_15': None,
     'damage_share': 0.12419532,
     'jungle_proximity': None,
     'support_proximity': None,
     'total_cs': 240,
     'total_kills': 3,
     'total_monster_kills': None,
     'total_assists': 12,
     'total_deaths': 6,
     'total_damage_taken': 27903,
     'total_vision_score': None},
    {'name': 'Heng',
     'champion_name': 'Udyr',
     'gd_15': None,
     'kills_assists_15': 0,
     'deaths_15': 0,
     'gold_share_post_15': None,
     'damage_share': 0.13

In [20]:
data[0].keys()

dict_keys(['id', 'start', 'patch', 'winner', 'duration', 'video', 'teams'])

In [21]:
data[0]['teams'].keys()

dict_keys(['BLUE', 'RED'])

In [22]:
data[0]['teams']['BLUE'].keys()

dict_keys(['name', 'total_turret_kills', 'total_inhibitor_kills', 'total_rift_herald_kills', 'total_dragon_kills', 'total_baron_kills', 'players'])

In [37]:
data[0]['teams']['BLUE']['players'][0].keys()

dict_keys(['name', 'champion_name', 'gd_15', 'kills_assists_15', 'deaths_15', 'gold_share_post_15', 'damage_share', 'jungle_proximity', 'support_proximity', 'total_cs', 'total_kills', 'total_monster_kills', 'total_assists', 'total_deaths', 'total_damage_taken', 'total_vision_score'])

### To remove
video, team_name, 'total_monster_kills', 'damage_share', 'total_vision_score'

## Normalize the JSON file into a Pandas DataFrame

Data is structured in a JSON structure that is inconvinient for data analysis. Converting nested JSON structures to Pandas DataFrames using https://medium.com/swlh/converting-nested-json-structures-to-pandas-dataframes-e8106c59976e

In [163]:
#Normalize the teams input
df_normalized_teams = pd.json_normalize(data)
df_normalized_teams.head()

id                      start  patch winner  duration  \
0  9498  2021-06-20T07:59:21+00:00  11.11    RED      3465   
1  9499  2021-06-20T06:15:59+00:00  11.11    RED      2232   
2  9500  2021-06-20T07:16:15+00:00  11.11    RED      1236   
3  9501  2021-06-20T07:18:36+00:00  11.11    RED      1693   
4  9504  2021-06-20T05:51:43+00:00  11.11   BLUE      2370   

                                      video         teams.BLUE.name  \
0  https://v.qq.com/x/page/l3254kzrmhg.html          Young Miracles   
1  https://v.qq.com/x/page/w3254dg95s4.html  Bilibili Gaming Junior   
2  https://v.qq.com/x/page/b325478obyw.html  Bilibili Gaming Junior   
3       https://youtu.be/YSNSi7ANhcY?t=4311              LGD Gaming   
4       https://youtu.be/6eZkzveawDc?t=1867            Liiv SANDBOX   

   teams.BLUE.total_turret_kills  teams.BLUE.total_inhibitor_kills  \
0                              4                               NaN   
1                              6                               NaN   
2                              0                               NaN   
3                              3                               NaN   
4                              7                               1.0   

   teams.BLUE.total_rift_herald_kills  teams.BLUE.total_dragon_kills  \
0                                 NaN                              2   
1                                 NaN                              3   
2                                 NaN                              0   
3                                 NaN                              1   
4                                 2.0                              4   

   teams.BLUE.total_baron_kills  \
0                             1   
1                             1   
2                             0   
3                             0   
4                             0   

                                  teams.BLUE.players          teams.RED.name  \
0  [{'name': 'Fangyuan', 'champion_name': 'Shen',...    Rogue Warriors Shark   
1  [{'name': 'Myths', 'champion_name': 'Kennen', ...  Top Esports Challenger   
2  [{'name': 'Myths', 'champion_name': 'Camille',...  Top Esports Challenger   
3  [{'name': 'Xiye', 'champion_name': 'Sett', 'gd...               JD Gaming   
4  [{'name': 'Summit', 'champion_name': 'Gnar', '...                      T1   

   teams.RED.total_turret_kills  teams.RED.total_inhibitor_kills  \
0                             9                              NaN   
1                            11                              NaN   
2                             7                              NaN   
3                             7                              NaN   
4                            10                              2.0   

   teams.RED.total_rift_herald_kills  teams.RED.total_dragon_kills  \
0                                NaN                             4   
1                                NaN                             3   
2                                NaN                             3   
3                                NaN                             3   
4                                0.0                             1   

   teams.RED.total_baron_kills  \
0                            1   
1                            1   
2                            0   
3                            1   
4                            1   

                                   teams.RED.players  
0  [{'name': 'PandaC', 'champion_name': 'Sett', '...  
1  [{'name': 'Wayward', 'champion_name': 'Sylas',...  
2  [{'name': 'Wayward', 'champion_name': 'Aatrox'...  
3  [{'name': 'Zoom', 'champion_name': 'Gwen', 'gd...  
4  [{'name': 'Canna', 'champion_name': 'Jayce', '...

In [164]:
df_normalized_teams.drop('video', axis=1, inplace = True)

In [165]:
df_normalized_teams.drop(['teams.BLUE.name', 'teams.RED.name'], axis=1, inplace=True)

In [24]:
df_normalized_teams['teams.BLUE.players'].explode()

0       {'name': 'Fangyuan', 'champion_name': 'Shen', ...
0       {'name': 'Heng', 'champion_name': 'Udyr', 'gd_...
0       {'name': 'Caipuxin', 'champion_name': 'LeBlanc...
0       {'name': 'Shaoye', 'champion_name': 'Kog'Maw',...
0       {'name': 'Famingjia', 'champion_name': 'Lulu',...
                              ...                        
1999    {'name': 'Flaai', 'champion_name': 'Sett', 'gd...
1999    {'name': 'Adampongo', 'champion_name': 'Jarvan...
1999    {'name': 'Necropolisak', 'champion_name': 'Ryz...
1999    {'name': 'Kneza', 'champion_name': 'Lucian', '...
1999    {'name': 'Phenix', 'champion_name': 'Lulu', 'g...
Name: teams.BLUE.players, Length: 10000, dtype: object

In [115]:
df_normalized_BLUE = pd.json_normalize(df_normalized_teams['teams.BLUE.players'].explode())
df_normalized_BLUE

name champion_name  gd_15  kills_assists_15  deaths_15  \
0         Fangyuan          Shen    NaN               0.0        0.0   
1             Heng          Udyr    NaN               0.0        0.0   
2         Caipuxin       LeBlanc    NaN               0.0        0.0   
3           Shaoye       Kog'Maw    NaN               0.0        0.0   
4        Famingjia          Lulu    NaN               0.0        0.0   
...            ...           ...    ...               ...        ...   
9995         Flaai          Sett    NaN               NaN        NaN   
9996     Adampongo     Jarvan IV    NaN               NaN        NaN   
9997  Necropolisak          Ryze    NaN               NaN        NaN   
9998         Kneza        Lucian    NaN               NaN        NaN   
9999        Phenix          Lulu    NaN               NaN        NaN   

      gold_share_post_15  damage_share  jungle_proximity  support_proximity  \
0                    NaN      0.124195               NaN                NaN   
1                    NaN      0.135611               NaN                NaN   
2                    NaN      0.323320               NaN                NaN   
3                    NaN      0.372636               NaN                NaN   
4                    NaN      0.044239               NaN                NaN   
...                  ...           ...               ...                ...   
9995                 NaN           NaN               NaN                NaN   
9996                 NaN           NaN               NaN                NaN   
9997                 NaN           NaN               NaN                NaN   
9998                 NaN           NaN               NaN                NaN   
9999                 NaN           NaN               NaN                NaN   

      total_cs  total_kills  total_monster_kills  total_assists  total_deaths  \
0        240.0          3.0                  NaN           12.0           6.0   
1        186.0          3.0                  NaN           15.0           6.0   
2        284.0          8.0                  NaN            4.0           3.0   
3        388.0          8.0                  NaN            9.0           5.0   
4         16.0          1.0                  NaN           14.0           6.0   
...        ...          ...                  ...            ...           ...   
9995     193.0          0.0                 16.0            6.0           4.0   
9996     169.0          0.0                152.0           14.0           2.0   
9997     258.0          5.0                 35.0            4.0           2.0   
9998     350.0         15.0                 40.0            5.0           0.0   
9999      11.0          2.0                  0.0           19.0           4.0   

      total_damage_taken  total_vision_score  
0                27903.0                 NaN  
1                34205.0                 NaN  
2                22290.0                 NaN  
3                23348.0                 NaN  
4                15708.0                 NaN  
...                  ...                 ...  
9995             28321.0                51.0  
9996             32735.0                46.0  
9997             15094.0                28.0  
9998             19019.0                62.0  
9999             12312.0                60.0  

[10000 rows x 16 columns]

In [26]:
df_normalized_RED = pd.json_normalize(df_normalized_teams['teams.RED.players'].explode(), )
df_normalized_RED

name champion_name  gd_15  kills_assists_15  deaths_15  \
0                    PandaC          Sett    NaN               0.0        0.0   
1           Eight (Lin Jie)       Taliyah    NaN               0.0        0.0   
2                    Xifeng        Qiyana    NaN               0.0        0.0   
3                     Kelin          Jhin    NaN               0.0        0.0   
4                     Michi         Karma    NaN               0.0        0.0   
...                     ...           ...    ...               ...        ...   
9995                 Kulvas       Camille    NaN               NaN        NaN   
9996  Hiro (Nguyên Đại Hải)  Miss Fortune    NaN               NaN        NaN   
9997               Jackisek       LeBlanc    NaN               NaN        NaN   
9998                 Smarty          Nami    NaN               NaN        NaN   
9999                 Savero         Viego    NaN               NaN        NaN   

      gold_share_post_15  damage_share  jungle_proximity  support_proximity  \
0                    NaN      0.279340               NaN                NaN   
1                    NaN      0.228947               NaN                NaN   
2                    NaN      0.182081               NaN                NaN   
3                    NaN      0.205698               NaN                NaN   
4                    NaN      0.103934               NaN                NaN   
...                  ...           ...               ...                ...   
9995                 NaN           NaN               NaN                NaN   
9996                 NaN           NaN               NaN                NaN   
9997                 NaN           NaN               NaN                NaN   
9998                 NaN           NaN               NaN                NaN   
9999                 NaN           NaN               NaN                NaN   

      total_cs  total_kills  total_monster_kills  total_assists  total_deaths  \
0        296.0          5.0                  NaN            8.0           5.0   
1        285.0          6.0                  NaN           11.0           5.0   
2        266.0          6.0                  NaN            5.0           3.0   
3        364.0          8.0                  NaN            6.0           4.0   
4         20.0          1.0                  NaN           14.0           6.0   
...        ...          ...                  ...            ...           ...   
9995     252.0          2.0                 16.0            4.0           5.0   
9996     270.0          7.0                  9.0            0.0           5.0   
9997     222.0          2.0                 12.0            7.0           3.0   
9998      10.0          1.0                  0.0            9.0           6.0   
9999     172.0          0.0                158.0            3.0           3.0   

      total_damage_taken  total_vision_score  
0                38556.0                 NaN  
1                23033.0                 NaN  
2                16575.0                 NaN  
3                18377.0                 NaN  
4                17048.0                 NaN  
...                  ...                 ...  
9995             27259.0                45.0  
9996             12090.0                40.0  
9997             23435.0                38.0  
9998             11427.0                82.0  
9999             27727.0                29.0  

[10000 rows x 16 columns]

### Get the game id to properly analyze the data

We have two different dataframes for team Blue and team Red, we can merge them on the game id. This will also be useful when we want to come back for the y parameter! 

In [84]:
# Extract the index corresponding to the game id 
get_index = df_normalized_teams['id'].tolist()
get_index[:10], len(get_index)

([9498, 9499, 9500, 9501, 9504, 9506, 9507, 9508, 9509, 9513], 2000)

In [86]:
import numpy as np

index_preproc = np.asarray([[index] * 5 for index in get_index])
index_preproc.shape

(2000, 5)

In [90]:
#reshape the array to 1D
## 5 is because there are 5 players per team
index_teams = index_preproc.reshape(len(df_normalized_teams) * 5).tolist()
index_teams[0:12]

[9498, 9498, 9498, 9498, 9498, 9499, 9499, 9499, 9499, 9499, 9500, 9500]

In [94]:
df_normalized_RED['index_teams'] = index_teams
df_normalized_BLUE['index_teams'] = index_teams

In [102]:
df_normalized_BLUE

name champion_name  gd_15  kills_assists_15  deaths_15  \
0         Fangyuan          Shen    NaN               0.0        0.0   
1             Heng          Udyr    NaN               0.0        0.0   
2         Caipuxin       LeBlanc    NaN               0.0        0.0   
3           Shaoye       Kog'Maw    NaN               0.0        0.0   
4        Famingjia          Lulu    NaN               0.0        0.0   
...            ...           ...    ...               ...        ...   
9995         Flaai          Sett    NaN               NaN        NaN   
9996     Adampongo     Jarvan IV    NaN               NaN        NaN   
9997  Necropolisak          Ryze    NaN               NaN        NaN   
9998         Kneza        Lucian    NaN               NaN        NaN   
9999        Phenix          Lulu    NaN               NaN        NaN   

      gold_share_post_15  damage_share  jungle_proximity  support_proximity  \
0                    NaN      0.124195               NaN                NaN   
1                    NaN      0.135611               NaN                NaN   
2                    NaN      0.323320               NaN                NaN   
3                    NaN      0.372636               NaN                NaN   
4                    NaN      0.044239               NaN                NaN   
...                  ...           ...               ...                ...   
9995                 NaN           NaN               NaN                NaN   
9996                 NaN           NaN               NaN                NaN   
9997                 NaN           NaN               NaN                NaN   
9998                 NaN           NaN               NaN                NaN   
9999                 NaN           NaN               NaN                NaN   

      total_cs  total_kills  total_monster_kills  total_assists  total_deaths  \
0        240.0          3.0                  NaN           12.0           6.0   
1        186.0          3.0                  NaN           15.0           6.0   
2        284.0          8.0                  NaN            4.0           3.0   
3        388.0          8.0                  NaN            9.0           5.0   
4         16.0          1.0                  NaN           14.0           6.0   
...        ...          ...                  ...            ...           ...   
9995     193.0          0.0                 16.0            6.0           4.0   
9996     169.0          0.0                152.0           14.0           2.0   
9997     258.0          5.0                 35.0            4.0           2.0   
9998     350.0         15.0                 40.0            5.0           0.0   
9999      11.0          2.0                  0.0           19.0           4.0   

      total_damage_taken  total_vision_score  index_teams  
0                27903.0                 NaN         9498  
1                34205.0                 NaN         9498  
2                22290.0                 NaN         9498  
3                23348.0                 NaN         9498  
4                15708.0                 NaN         9498  
...                  ...                 ...          ...  
9995             28321.0                51.0        19525  
9996             32735.0                46.0        19525  
9997             15094.0                28.0        19525  
9998             19019.0                62.0        19525  
9999             12312.0                60.0        19525  

[10000 rows x 17 columns]

In [103]:
df_normalized_RED

name champion_name  gd_15  kills_assists_15  deaths_15  \
0                    PandaC          Sett    NaN               0.0        0.0   
1           Eight (Lin Jie)       Taliyah    NaN               0.0        0.0   
2                    Xifeng        Qiyana    NaN               0.0        0.0   
3                     Kelin          Jhin    NaN               0.0        0.0   
4                     Michi         Karma    NaN               0.0        0.0   
...                     ...           ...    ...               ...        ...   
9995                 Kulvas       Camille    NaN               NaN        NaN   
9996  Hiro (Nguyên Đại Hải)  Miss Fortune    NaN               NaN        NaN   
9997               Jackisek       LeBlanc    NaN               NaN        NaN   
9998                 Smarty          Nami    NaN               NaN        NaN   
9999                 Savero         Viego    NaN               NaN        NaN   

      gold_share_post_15  damage_share  jungle_proximity  support_proximity  \
0                    NaN      0.279340               NaN                NaN   
1                    NaN      0.228947               NaN                NaN   
2                    NaN      0.182081               NaN                NaN   
3                    NaN      0.205698               NaN                NaN   
4                    NaN      0.103934               NaN                NaN   
...                  ...           ...               ...                ...   
9995                 NaN           NaN               NaN                NaN   
9996                 NaN           NaN               NaN                NaN   
9997                 NaN           NaN               NaN                NaN   
9998                 NaN           NaN               NaN                NaN   
9999                 NaN           NaN               NaN                NaN   

      total_cs  total_kills  total_monster_kills  total_assists  total_deaths  \
0        296.0          5.0                  NaN            8.0           5.0   
1        285.0          6.0                  NaN           11.0           5.0   
2        266.0          6.0                  NaN            5.0           3.0   
3        364.0          8.0                  NaN            6.0           4.0   
4         20.0          1.0                  NaN           14.0           6.0   
...        ...          ...                  ...            ...           ...   
9995     252.0          2.0                 16.0            4.0           5.0   
9996     270.0          7.0                  9.0            0.0           5.0   
9997     222.0          2.0                 12.0            7.0           3.0   
9998      10.0          1.0                  0.0            9.0           6.0   
9999     172.0          0.0                158.0            3.0           3.0   

      total_damage_taken  total_vision_score  index_teams  
0                38556.0                 NaN         9498  
1                23033.0                 NaN         9498  
2                16575.0                 NaN         9498  
3                18377.0                 NaN         9498  
4                17048.0                 NaN         9498  
...                  ...                 ...          ...  
9995             27259.0                45.0        19525  
9996             12090.0                40.0        19525  
9997             23435.0                38.0        19525  
9998             11427.0                82.0        19525  
9999             27727.0                29.0        19525  

[10000 rows x 17 columns]

There are 3 created dataframes important in this section:
```df_normalized_teams, df_normalized_BLUE and df_normalized_RED```

# Preprocess the data

## For the team data

In [216]:
df_normalized_teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   id                                  2000 non-null   int64  
 1   patch                               2000 non-null   object 
 2   winner                              2000 non-null   object 
 3   duration                            2000 non-null   int64  
 4   teams.BLUE.total_turret_kills       2000 non-null   int64  
 5   teams.BLUE.total_inhibitor_kills    2000 non-null   float64
 6   teams.BLUE.total_rift_herald_kills  2000 non-null   float64
 7   teams.BLUE.total_dragon_kills       2000 non-null   int64  
 8   teams.BLUE.total_baron_kills        2000 non-null   int64  
 9   teams.BLUE.players                  2000 non-null   object 
 10  teams.RED.total_turret_kills        2000 non-null   int64  
 11  teams.RED.total_inhibitor_kills     2000 no

### Get the year the game was played

In [167]:
df_normalized_teams['start'] = pd.to_datetime(df_normalized_teams['start'])
df_normalized_teams['year'] = pd.DatetimeIndex(df_normalized_teams['start']).year
df_normalized_teams.year.unique()

array([2021])

In [168]:
# We don't need the rest of the date so we can drop the data
df_normalized_teams.drop('start', axis=1, inplace=True)

In [190]:
winner = [1 if value == 'BLUE' else 0 for value in df_normalized_teams.winner]
len(winner), sum(winner)

(2000, 1053)

In [194]:
from sklearn.preprocessing import LabelEncoder

y = LabelEncoder().fit(df_normalized_teams.winner).transform(df_normalized_teams.winner)
y

array([1, 1, 1, ..., 1, 1, 0])

### Check for null data

In [204]:
df_normalized_teams['teams.BLUE.total_inhibitor_kills'].unique()

array([1., 0., 2., 3., 4., 5., 6., 7.])

In [213]:
median_BLUE_total_inhibitor_kills = df_normalized_teams['teams.BLUE.total_inhibitor_kills'].median()
df_normalized_teams['teams.BLUE.total_inhibitor_kills'] = df_normalized_teams[
            'teams.BLUE.total_inhibitor_kills'].replace(np.nan, median_BLUE_total_inhibitor_kills)

df_normalized_teams['teams.BLUE.total_inhibitor_kills'].unique(), median_BLUE_total_inhibitor_kills

(array([1., 0., 2., 3., 4., 5., 6., 7.]), 1.0)

In [210]:
df_normalized_teams['teams.BLUE.total_rift_herald_kills'].unique()

array([nan,  2.,  0.,  1.])

In [212]:
median_BLUE_total_rift_herald_kills = df_normalized_teams['teams.BLUE.total_rift_herald_kills'].median()
df_normalized_teams['teams.BLUE.total_rift_herald_kills'] = df_normalized_teams[
            'teams.BLUE.total_rift_herald_kills'].replace(np.nan, median_BLUE_total_rift_herald_kills)

df_normalized_teams['teams.BLUE.total_rift_herald_kills'].unique(), median_BLUE_total_rift_herald_kills

(array([1., 2., 0.]), 1.0)

In [158]:
df_normalized_teams['teams.RED.total_inhibitor_kills'].unique()

array([nan,  2.,  0.,  1.,  3.,  5.,  4.,  6.])

In [214]:
median_RED_total_inhibitor_kills = df_normalized_teams['teams.RED.total_inhibitor_kills'].median()
df_normalized_teams['teams.RED.total_inhibitor_kills'] = df_normalized_teams[
            'teams.RED.total_inhibitor_kills'].replace(np.nan, median_RED_total_inhibitor_kills)

df_normalized_teams['teams.RED.total_inhibitor_kills'].unique(), median_RED_total_inhibitor_kills

(array([0., 2., 1., 3., 5., 4., 6.]), 0.0)

In [157]:
df_normalized_teams['teams.RED.total_rift_herald_kills'].unique()

array([nan,  0.,  2.,  1.])

In [215]:
median_RED_total_rift_herald_kills = df_normalized_teams['teams.RED.total_rift_herald_kills'].median()
df_normalized_teams['teams.RED.total_rift_herald_kills'] = df_normalized_teams[
            'teams.RED.total_rift_herald_kills'].replace(np.nan, median_RED_total_rift_herald_kills)

df_normalized_teams['teams.RED.total_rift_herald_kills'].unique(), median_RED_total_rift_herald_kills

(array([1., 0., 2.]), 1.0)

## For the players data

In [171]:
df_normalized_BLUE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   name                 10000 non-null  object 
 1   champion_name        10000 non-null  object 
 2   gd_15                7230 non-null   float64
 3   kills_assists_15     9315 non-null   float64
 4   deaths_15            9315 non-null   float64
 5   gold_share_post_15   260 non-null    float64
 6   damage_share         8720 non-null   float64
 7   jungle_proximity     7230 non-null   float64
 8   support_proximity    7230 non-null   float64
 9   total_cs             9405 non-null   float64
 10  total_kills          9405 non-null   float64
 11  total_monster_kills  9042 non-null   float64
 12  total_assists        9405 non-null   float64
 13  total_deaths         9405 non-null   float64
 14  total_damage_taken   9375 non-null   float64
 15  total_vision_score   9325 non-null   

In [196]:
df_normalized_BLUE.columns

Index(['name', 'champion_name', 'gd_15', 'kills_assists_15', 'deaths_15',
       'gold_share_post_15', 'damage_share', 'jungle_proximity',
       'support_proximity', 'total_cs', 'total_kills', 'total_monster_kills',
       'total_assists', 'total_deaths', 'total_damage_taken',
       'total_vision_score'],
      dtype='object')

In [229]:
for column in df_normalized_BLUE.columns[2:]:
    print(column, '->', df_normalized_BLUE[column].median())
    print(column, '->', df_normalized_BLUE[column].mean())
    print(column, '->', df_normalized_BLUE[column].mode())
    print(' ')

gd_15 -> 80.0
gd_15 -> 81.03706777316737
gd_15 -> 0     70.0
1    344.0
dtype: float64
 
kills_assists_15 -> 1.0
kills_assists_15 -> 1.8892109500805152
kills_assists_15 -> 0    0.0
dtype: float64
 
deaths_15 -> 0.0
deaths_15 -> 0.6718196457326893
deaths_15 -> 0    0.0
dtype: float64
 
gold_share_post_15 -> 0.34958982
gold_share_post_15 -> 0.4392004267615386
gold_share_post_15 -> 0    1.0
dtype: float64
 
damage_share -> 0.20194653
damage_share -> 0.2000000001534396
damage_share -> 0    0.186096
1    0.274648
dtype: float64
 
jungle_proximity -> 0.19450798
jungle_proximity -> 0.33486622220230877
jungle_proximity -> 0    1.0
dtype: float64
 
support_proximity -> 0.242924215
support_proximity -> 0.4061813671669669
support_proximity -> 0    1.0
dtype: float64
 
total_cs -> 208.0
total_cs -> 193.42977139819246
total_cs -> 0    33.0
dtype: float64
 
total_kills -> 2.0
total_kills -> 2.993939393939394
total_kills -> 0    1.0
dtype: float64
 
total_monster_kills -> 14.0
total_monster_kills -> 

In [197]:
df_normalized_BLUE.champion_name

0            Shen
1            Udyr
2         LeBlanc
3         Kog'Maw
4            Lulu
          ...    
9995         Sett
9996    Jarvan IV
9997         Ryze
9998       Lucian
9999         Lulu
Name: champion_name, Length: 10000, dtype: object